/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.gltf 
Author: JazOone (https://sketchfab.com/JazOone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-6164a883f57f4f13938c3c5999bc0e1f
Title: SpaceShip
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/spaceship.gltf')
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Starship_Material003_0.geometry} material={materials['Material.003']} scale={1} />
    </group>
  )
}

useGLTF.preload('/spaceship.gltf')
