/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 enemy.gltf 
Author: Speedy BOY (https://sketchfab.com/speedy2311playz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-vfx-1b10dafa65bd4290985d4602b82c55e1
Title: ANIME VFX
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/enemy.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.009']} position={[-0.042, 1.508, 0]} rotation={[0.333, -0.685, 0.602]} scale={1.19} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.007']} position={[-0.043, 1.509, -0.006]} rotation={[0, 0, -0.052]} scale={0.973} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.008']} position={[-0.055, 1.508, 0]} rotation={[-3.012, 0.811, 2.526]} scale={1.06} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.008']} position={[0, 1.827, -0.067]} rotation={[2.377, 0.416, 0.13]} scale={[2.364, 4.549, 2.364]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.007']} position={[-0.052, 1.615, 0.011]} scale={[1.953, 3.758, 1.953]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.008']} position={[-0.052, 0.583, 0.011]} scale={[1.729, 3.327, 1.729]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.008']} position={[-0.047, 0.329, 0.011]} scale={[0.748, 1.438, 0.748]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.009']} position={[0.015, 1.781, -0.14]} rotation={[0.692, 0.004, 0.24]} scale={[2.816, 5.418, 2.816]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.008']} position={[-0.047, 0.256, 0.011]} scale={[0.542, 1.042, 0.542]} />
    </group>
  )
}

useGLTF.preload('/enemy.gltf')
